name: OrangeHRM Cypress CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    env:
      CYPRESS_USERNAME: ${{ secrets.CYPRESS_USERNAME }}
      CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      # ðŸ”¹ Clean old reports
      - name: Clean old reports
        run: |
          rm -rf reports
          mkdir -p reports

      # ðŸ”¹ Run Cypress tests
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          config: baseUrl=https://opensource-demo.orangehrmlive.com
        continue-on-error: true

      # ðŸ”¹ Generate Mochawesome Report
      - name: Generate Mochawesome Report
        if: always()
        run: |
          if compgen -G "cypress/reports/*.json" > /dev/null; then
            npx mochawesome-merge cypress/reports/*.json > cypress/reports/output.json
            npx marge cypress/reports/output.json -f report -o reports
          else
            echo "No JSON files to merge"
          fi

      - name: Upload Mochawesome Report
        uses: actions/upload-artifact@v4
        with:
            name: mochawesome-report
            path: cypress/reports

      # ðŸ”¹ Generate Allure Report in same folder
      - name: Generate Allure Report
        if: always()
        run: |
          if [ -d "allure-results" ] && [ "$(ls -A allure-results)" ]; then
            npx allure generate allure-results --clean -o reports
          else
            echo "No Allure results found"
          fi

      # ðŸ”¹ Deploy combined reports to GitHub Pages
      - name: Deploy Reports to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./reports
          publish_branch: gh-pages
          user_name: 'github-actions'
          user_email: 'github-actions@github.com'

      # ðŸ”¹ Print single report URL
      - name: Print report URL
        if: always()
        run: |
          USER_NAME=${GITHUB_REPOSITORY%%/*}
          REPO_NAME=${GITHUB_REPOSITORY#*/}
          echo "=============================================="
          echo "ðŸŽ¯ Open combined Report: https://${USER_NAME}.github.io/${REPO_NAME}/"
          echo "=============================================="
