name: OrangeHRM Cypress CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    env:
      CYPRESS_USERNAME: ${{ secrets.CYPRESS_USERNAME }}
      CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      # ðŸ”¹ Clean old reports
      - name: Clean old reports
        run: |
          npm run cypress:clean
          mkdir -p reports/allure

      # ðŸ”¹ Run Cypress tests
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          config: baseUrl=https://opensource-demo.orangehrmlive.com
        continue-on-error: true

      # ðŸ”¹ Generate Allure Report
      - name: Generate Allure Report
        if: always()
        run: |
          if [ -d "allure-results" ] && [ "$(ls -A allure-results)" ]; then
            npm run allure:generate
          else
            echo "No Allure results found"
          fi

      # ðŸ”¹ Deploy Reports to GitHub Pages
      - name: Deploy Reports to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./reports
          publish_branch: gh-pages

      # ðŸ”¹ Print Report URL
      - name: Print report URL
        if: always()
        run: |
          USER_NAME=${GITHUB_REPOSITORY%%/*}
          REPO_NAME=${GITHUB_REPOSITORY#*/}

          echo "=============================================="
          echo "ðŸŽ¯ Test Report URL:"
          echo "âœ¨ Allure Report:"
          echo "https://${USER_NAME}.github.io/${REPO_NAME}/allure/"
          echo "=============================================="
